export const copy = {
  storeTagline: "Traditional pooja & homam essentials",
  storeTamilLine: "நாட்டு மருந்துகள் · கும்பாபிஷேகம் · கணபதி ஹோமம் · நவக்கிரக ஹோமம் · பூஜை சாமான்கள்",
  storeLocationLine: "R.S. Puram, Coimbatore",
  heroBody:
    "Samagri for daily pooja, materials for Ganapathy and Navagraha Homam, kumbabishekam requirements, and traditional naattu marundhu — from the counter in R.S. Puram.",
  shopPooja: "Shop pooja essentials",
  shopNow: "Shop Collection",
  shopHomam: "Homam collections",
  viewAllProducts: "View all products",
  browseCatalog: "Browse the catalog",
  startHere: "Start here",
  shopByNeed: "Shop by what you need",
  allProducts: "All products",
  featuredAisles: "Collections",
  featuredAislesTitle: "Pooja, homam, temple, and naattu marundhu",
  explore: "Explore",
  popularPooja: "Most loved products",
  popularPoojaBody:
    "Camphor, kumkum, sambrani, wicks — high-quality essentials our community trusts for their daily rituals.",
  popularPoojaEyebrow: "Essentials",
  popularPoojaCta: "View all essentials",
  shopByRitual: "Shop by ritual",
  shopByRitualEyebrow: "Curated selection",
  exploreCategories: "Explore all categories",
  ganapathyRail: "Ganapathy Homam",
  ganapathyRailBody: "Kits and samagri commonly sold for Ganapathy Homam. Confirm contents at the shop.",
  navagrahaRail: "Navagraha Homam",
  navagrahaRailBody: "Navadhanya, samagri, and a shop-packed kit.",
  kumbhaRail: "Kumbabishekam",
  kumbhaRailBody: "Kalasam and packed materials often bought for temple work.",
  herbalRail: "Naattu marundhu",
  herbalRailBody: "Traditional herbal products from the shop. Not medicines.",
  visitTitle: "Visit the store",
  visitBody:
    "Walk in at R.S. Puram, or call before you come for homam and kumbabishekam quantities.",
  searchPlaceholder: "Search கற்பூரம், camphor, homam, குங்குமம்…",
  physicalShop: "The physical shop",
  openMap: "Open in Google Maps",
  callShop: "Call the shop",
} as const;
